### ISSUE TITLE
画像の上にキャプションを表示するオプションを作る

### ISSUE THREAD

**Issue by aiotter** [aocsj/website#112]
キャプションの位置はこのように指定することで上部に配置できます。
```css
figure {
  display: table;
}
figcaption {
  display: table-caption;
  caption-side: top;
}
```
cf. https://www.w3.org/Style/Examples/007/figures.en.html

Image ブロックの挿入時のオプションを追加し、画像の上にキャプションを表示する設定を作成します。
https://github.com/aocsj/website/blob/ac08a9ece090045416b6f8a5fce2861de6dbb2e5/static/admin/index.html#L13-L41
