### ISSUE TITLE
見出しと本文の間にスペースを作る

### ISSUE THREAD

**Issue by aiotter** [aocsj/website#17]
本文
本文
## 見出し

---
上記のような構成において、本文と見出しの間にスペースがないため読みにくくなっています。
CSSを編集して、本文と見出しの間のパディングを大きくする必要があります。

**Comment by aiotter** [comment]
h2 の margin-top が 1 rem になってるので、2 rem にするとちょうどよくなりそう。
```css
h2 {
    margin-top: 2rem;
    font-size: 1.5rem;
}
```
